# Automatidata Project:
Statistical Analysis

**The purpose** of this project is to demostrate knowledge of how to prepare, create, and analyze A/B tests. Your A/B test results should aim to find ways to generate more revenue for taxi cab drivers.

**The goal** is to apply descriptive statistics and hypothesis testing in Python. The goal for this A/B test is to sample data and analyze whether there is a relationship between payment type and fare amount. For example: discover if customers who use credit cards pay higher fare amounts than customers who use cash.

### This activity has 4 parts:
**Part 1:** Imports and data loading
- Import necessary data packages for hypothesis testing

**Part 2:** Conduct EDA(This has been done on previous notebook) and hypothesis testing
- Formulate your null hypothesis and alternative hypothesis? 

**Part 3:** Communicate insights with stakeholders
- Key business insight(s) emerged from your A/B test
- Propose business recommendations according to our results

# PLAN 
- primary goal is to aswer to the question that : "Is there a relationship between fare amount and payment method."

# Analyze:

### Task 1 : Import packages and data loading

In [2]:
import pandas as pd
from scipy import stats

In [3]:
taxi_data = pd.read_csv("2017_Yellow_Taxi_Trip_Data.csv", index_col = 0)

### Task 2 : Data exploration
Exploratory Data Analysis for thid dataset has already been performed in another notebook.

In [4]:
# Descriptive statistics
taxi_data.describe(include='all')

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,22699.000000,22699,22699,22699.000000,22699.000000,22699.000000,22699,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000
unique,NaN,22687,22688,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,07/03/2017 3:45:19 PM,10/18/2017 8:07:45 PM,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,2,NaN,NaN,NaN,22600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.556236,NaN,NaN,1.642319,2.913313,1.043394,NaN,162.412353,161.527997,1.336887,13.026629,0.333275,0.497445,1.835781,0.312542,0.299551,16.310502
std,0.496838,NaN,NaN,1.285231,3.653171,0.708391,NaN,66.633373,70.139691,0.496211,13.243791,0.463097,0.039465,2.800626,1.399212,0.015673,16.097295
min,1.000000,NaN,NaN,0.000000,0.000000,1.000000,NaN,1.000000,1.000000,1.000000,-120.000000,-1.000000,-0.500000,0.000000,0.000000,-0.300000,-120.300000
25%,1.000000,NaN,NaN,1.000000,0.990000,1.000000,NaN,114.000000,112.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.300000,8.750000
50%,2.000000,NaN,NaN,1.000000,1.610000,1.000000,NaN,162.000000,162.000000,1.000000,9.500000,0.000000,0.500000,1.350000,0.000000,0.300000,11.800000
75%,2.000000,NaN,NaN,2.000000,3.060000,1.000000,NaN,233.000000,233.000000,2.000000,14.500000,0.500000,0.500000,2.450000,0.000000,0.300000,17.800000
max,2.000000,NaN,NaN,6.000000,33.960000,99.000000,NaN,265.000000,265.000000,4.000000,999.990000,4.500000,0.500000,200.000000,19.100000,0.300000,1200.290000

**Note:** In the dataset, `payment_type` is encoded in integers:
*   1: Credit card
*   2: Cash
*   3: No charge
*   4: Dispute
*   5: Unknown

- Since we are interested in the relationship between payment type and fare amount, we can look into the fare amount per each category 0f payment type.

In [9]:
group_payment_fare = taxi_data[['payment_type', 'fare_amount']].groupby('payment_type').mean('fare_amount').reset_index()
group_payment_fare

   payment_type  fare_amount
0             1    13.429748
1             2    12.213546
2             3    12.186116
3             4     9.913043

- As we can see, the mean fare amount of customers who paid with their crredit card is higher than the average fare amount of other type payments.
- However, the observed difference might be due to the random sampling and chance. In order to evaluate that if the difference is statistically significant, we can perform a hypothesis testing.

### Task 3 : Hypothesis testing

- The goal here is to conduct a two-sample t-test following the next steps:
1.   State the null hypothesis and the alternative hypothesis
2.   Choose a signficance level
3.   Find the p-value
4.   Reject or fail to reject the null hypothesis

**1. State the null and alternative hypothesis:**

**Null Hypothesis ($H_0$):** 
    The difference in the observed average of fare amount for different payment types is due to the chance. And there is no difference in the average of fare amounts observed for customers paying with credit cards and those who pay with cash.
    
**Alternative Hypothesis ($H_A$):**
    The difference in the observed average of fare amount for different payment types is statistically significant. There is a difference in the average fare amount between customers who pay with cedit car and others who use cash.

**2. Choose a significance level:**
    
   Here we use 5% significance level.

**3. Find the p-value:**

In [18]:
credit_data = taxi_data[taxi_data['payment_type']==1]['fare_amount']
cash_data = taxi_data[taxi_data['payment_type']==2]['fare_amount']

In [19]:
stats.ttest_ind(a=credit_data, b=cash_data, equal_var=False)

TtestResult(statistic=6.866800855655372, pvalue=6.797387473030518e-12, df=16675.48547403633)

**4. Reject or fail to reject the null hypothesis:**

Since the p-value=6.8e-12 is less than 0.05, we reject the null hypothesis. Therefore, we can say that there is a statistically significant difference in the average fare amount between customers who use credit cards and customers who use cash.

## Insights:

1.   The key business insight is that encouraging customers to pay with credit cards can generate more revenue for taxi cab drivers. 

2.   This project requires an assumption that passengers were forced to pay one way or the other, and that once informed of this requirement, they always complied with it. The data was not collected this way; so, an assumption had to be made to randomly group data entries to perform an A/B test. This dataset does not account for other likely explanations. For example, riders might not carry lots of cash, so it's easier to pay for longer/farther trips with a credit card. In other words, it's far more likely that fare amount determines payment type, rather than vice versa.